version: "3.9"

services:
  application: 
    build: back-end/
    ports:
      - "8080:8080"
    environment:
      - APP_DB=mysql
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - database
      - broker
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_PASSWORD=secret2
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
    ports:
      - 33050:3306/tcp
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - database
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15692:15692"
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - broker
  front-end:
    build: front-end/
    ports:
      - "8081:5173"
  data-generator:
    depends_on:
      - rabbitmq
    build: data-generator/


networks:
  database:
    driver: bridge
  broker:
    driver: bridge
